version: 2.1

jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: public
    steps:
      - checkout

      # Initialize submodules
      - run:
          name: "Initialize and update git submodules"
          command: |
            git submodule update --init --recursive

      # Display the project structure
      - run:
          name: "List project files"
          command: ls -la

      # Build the Hugo site
      - run:
          name: "Build Hugo site"
          command: hugo -v -d ./public

      # Verify build output
      - run:
          name: "Verify build output"
          command: ls -la ./public

      # Deploy to build repository
      - run:
          name: "Deploy to build repository"
          command: |
            cd public
            git init
            git remote add origin https://github.com/obinkwon/obinkwon.github.io.git
            git add .
            git config --global user.name "CircleCI Bot"
            git config --global user.email "noreply@example.com"
            git commit -m "Automated publish to build-repo [ci skip]"
            git push --force origin main
