version: 2.1

workflows:
  version: 2
  deploy:
    jobs:
      - build

# 빌드 작업을 정의한 jobs 스크립트 형식으로 작성
jobs:
  # job의 이름을 정의
  build: 
    # 빌드를 실행할 도커 이미지를 설정한다.
    # circleci에서 제공하는 이미지를 사용해야 한다.
    docker:
      - image: circleci/node:14
    # Deploy의 과정을 한단계씩 정의한다.
    steps:
      # 소스를 checkout 하는 과정
      - checkout
      # 코드 전체를 컴파일 하는 과정
      - run:
          name: Deploy to Build Repository
          command: |
            git config --global user.name "obinkwon"
            git config --global user.email "obin0125@gmail.com"
            cd public
            git init
            git remote add origin https://github.com/obinkwon/obinkwon.github.io.git
            git add .
            git commit -m "Deploy from CircleCI"
            git push --force origin main
