version: 2.1

workflows:
  version: 2
  build:
    jobs:
      # Clone the repository
      - checkout

      # Install Hugo using Go
      - setup:
          name: Install Hugo
          docker:
            - image: circleci/golang:1.18 # Use a Go base image
          steps:
            - run:
                name: Install Hugo
                command: |
                  wget https://github.com/gohugoio/hugo/releases/download/v0.84.0/hugo_0.84.0_Linux-64bit.deb
                  sudo dpkg -i hugo_0.84.0_Linux-64bit.deb

      # Build Hugo site
      - build:
          name: Build Hugo Site
          docker:
            - image: circleci/golang:1.18
          steps:
            - checkout
            - run:
                name: Build Hugo
                command: hugo

      # Deploy the site
      - deploy:
          name: Deploy Hugo Site
          docker:
            - image: circleci/golang:1.18
          steps:
            - checkout
            - run:
                name: Copy build files
                command: echo 'complete'
