version: 2.1

workflows:
  build-deploy:
    jobs:
      - build

# 빌드 작업을 정의한 jobs 스크립트 형식으로 작성
jobs:
  # job의 이름을 정의, 굳이 build로 할 필요는 없지만 일반적으로 build를 사용한다.
  build:
  	# 빌드를 실행할 도커 이미지를 설정한다.
    # circleci에서 제공하는 이미지를 사용해야 한다.
    docker:
      # Ethereum의 프로그래밍 언어인 Go 컴파일을 해야하므로 go 이미지 세팅
      - image: circleci/golang:1.9
	
    # Go의 workspace를 설정해준다.
    working_directory: /go/src/github.com/Votereum/votereum-core
    
    steps:
    # Deploy의 과정을 한단계씩 정의한다.
      # 소스를 checkout 하는 과정
      - checkout
      - run: 
        name: Install Hugo
        command: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.84.0/hugo_0.84.0_Linux-64bit.deb
          sudo dpkg -i hugo_0.84.0_Linux-64bit.deb
      # 코드 전체를 컴파일 하는 과정
      - run: hugo
      # 테스트 성공시 good 출력
      - run: echo "good"