version: 2.1

workflows:
  build-deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    
    steps:
      - checkout
      - run:
          name: HUGO config file copy
          command:  |
            pwd
            ls -la
            cp hugo.toml config.toml
      - run:
          name: HUGO build
          command: hugo --baseURL "https://obinkwon.github.io/"
      - run:
          name: HUGO deploy repo clone
          command:  |
            git clone https://github.com/obinkwon/obinkwon.github.io.git
            cp -rf public/* obinkwon.github.io/
      - run:
          name: HUGO deploy
          command:  |
            cd obinkwon.github.io/ 
            ls -la
            git add .
            git config --global user.email "noreply@example.com"
            git config --global user.name "CircleCI Bot"
            git commit -m "Automated publish to obinkwon.github.io"
            git push origin main
